/* One followed series, two separately scored divisions. */
const CARSHub=(()=>{
 const series='CARS Tour',tabs={overview:'Overview',schedule:'Schedule',standings:'Standings',teams:'Teams & Drivers',results:'Results',tracks:'Tracks'},names={LMSC:'Late Model Stock Cars',PLM:'Pro Late Models'};
 let data=null,loaded=0,pending=null,error='',division='LMSC',eventId='',session='Race',sort='Position',ascending=true;
 const esc=x=>escapeHtml(String(x??'')),season=()=>String(new Date().getFullYear()),rows=k=>(data?.[k]||[]).filter(r=>!r.Season||r.Season===season());
 const configured=()=>!!window.RC_CARS_CONFIG?.feedUrl,protectedMode=()=>typeof Spoilers!=='undefined'&&Spoilers.protected(series);
 const safe=s=>{try{const u=new URL(s);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}};
 const img=(s,c='cars-logo')=>safe(s)?`<img class="${c}" src="${esc(safe(s))}" alt="" loading="lazy" onerror="this.hidden=true">`:'';
 const profile=r=>rows('Drivers').find(d=>d.Division===r.Division&&d['Driver ID']===r['Driver ID']);
 const identity=r=>`<span class="cars-identity">${img(profile(r)?.['Number Image URL'],'cars-number-image')||`<b>#${esc(r.Number)}</b>`}<span><strong>${esc(profile(r)?.Driver||r.Driver)}</strong><small>${esc(profile(r)?.Team||'')}</small></span></span>`;
 const switcher=()=>`<div class="cars-divisions" role="group" aria-label="CARS Tour division">${Object.entries(names).map(([k,n])=>`<button data-cars-division="${k}" aria-pressed="${division===k}"><b>${k}</b><small>${n}</small></button>`).join('')}</div>`;
 const standings=d=>rows('Standings').filter(r=>r.Division===d).sort((a,b)=>Number(a.Position)-Number(b.Position));
 const sourceNote=d=>{const r=standings(d)[0];return r?`<p class="f1-data-note">${esc(d)} Points as of ${esc(formatDate(r['As Of']))}${safe(r['Source URL'])?` · <a href="${esc(safe(r['Source URL']))}" target="_blank" rel="noopener">Official Standings</a>`:''}</p>`:'<p>Standings are not available yet.</p>';};
 const note=()=>`${error?`<p class="f1-warning">${esc(error)}</p>`:''}${rows('Status').some(s=>s.State==='RETAINED')?'<p class="f1-data-note">The latest automatic update was unavailable. Saved standings are shown with their publication dates.</p>':''}`;
 async function load(){if(!configured())return;if(pending)return pending;if(data&&Date.now()-loaded<60000)return;
  pending=(async()=>{try{const raw=await fetchSheet(window.RC_CARS_CONFIG.feedUrl),next={};for(const r of raw){if(!['Events','Sessions','Tracks','Drivers','Teams','Standings','Results','Status'].includes(r.Kind))continue;const v=JSON.parse(r.Data);if(!v||typeof v!=='object'||Array.isArray(v))throw Error('Invalid CARS row');(next[r.Kind]??=[]).push(v);}if(!next.Events?.length)throw Error('CARS events missing');data=next;loaded=Date.now();error='';}catch(e){error='CARS Tour update unavailable. '+(data?'Showing the last loaded data.':'Please try again later.');console.warn('CARS Tour',e.message);}finally{pending=null;}})();return pending;
 }
 function install(){if(!data)return;const tracks=rows('Tracks').map(t=>({source:'cars',trackId:'cars-'+t['Track ID'],name:t['Track Name Override']||t['Track Name'],city:t.City,state:t.State,type:t['Track Type'],surface:t.Surface,length:t['Track Length'],imageUrl:t['Track Image URL'],mapUrl:t['Track Map URL']}));
  const races=[],sessions=[];
  for(const e of rows('Events').filter(e=>!/^cancelled|canceled$/i.test(e.Status))){
   const ss=rows('Sessions').filter(s=>s['Event ID']===e['Event ID']),raceSessions=ss.filter(s=>/^race$/i.test(s.Session)&&!/^cancelled|canceled$/i.test(s.Status));
   // Earliest known race time is only used when every race has a published time.
   const minutes=t=>{const m=String(t).match(/^(\d{1,2}):(\d\d)\s*(AM|PM)$/i);return m?(Number(m[1])%12+(/pm/i.test(m[3])?12:0))*60+Number(m[2]):Infinity;};
   const sorted=[...raceSessions].sort((a,b)=>(a.Date||e.Date).localeCompare(b.Date||e.Date)||minutes(a['Time ET'])-minutes(b['Time ET']));
   const r={series,raceId:'cars-'+e['Event ID'],carsEventId:e['Event ID'],event:e.Event,trackId:'cars-'+e['Track ID'],date:sorted[0]?.Date||e.Date,time:sorted.length&&sorted.every(s=>Number.isFinite(minutes(s['Time ET'])))?sorted[0]['Time ET']:'TBD',network:e.Network||'',notes:[e.Divisions,e.Status==='Postponed'?'Postponed':e.Notes].filter(Boolean).join(' · ')};races.push(r);
   ss.forEach(s=>sessions.push({series,raceId:r.raceId,trackId:r.trackId,session:s.Division+' '+s.Session,type:/race/i.test(s.Session)?'Race':/qual/i.test(s.Session)?'Qualifying':'Practice',date:s.Date||e.Date,time:s['Time ET']||'TBD',notes:/Cancelled|Postponed/i.test(s.Status)?s.Status:''}));
  }
  allRaces=allRaces.filter(r=>![series,'CARS Tour LMSC'].includes(r.series)).concat(races);allSessions=allSessions.filter(r=>![series,'CARS Tour LMSC'].includes(r.series)).concat(sessions);allTracks=allTracks.filter(t=>t.source!=='cars').concat(tracks);
 }
 const resultRows=()=>rows('Results').filter(r=>r['Event ID']&&r.Division&&r.Session&&r.Driver&&Number(r.Position)>0);
 function table(rs,fields){return `<div class="f1-table-wrap"><table class="cars-table"><thead><tr>${fields.map(f=>`<th>${esc(f)}</th>`).join('')}</tr></thead><tbody>${rs.map(r=>`<tr>${fields.map(f=>`<td>${f==='Driver'?identity(r):f==='Gap'?(r.Gap?esc(r.Gap):'—'):esc(r[f]||'—')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`;}
 function overview(el){const next=racesFor(series).find(r=>r.date>=localIsoDate());el.innerHTML=`${note()}${next?`<section class="f1-feature event-photo-tile cars-next">${racePhotoMarkup(next)}<p class="f1-kicker">Next CARS Tour Weekend</p><h2>${esc(next.event)}</h2><p>${esc(formatDate(next.date))} · ${esc(RaceDisplay.time(next.time))}</p><p>${esc(next.notes)}</p><button class="nascar-schedule-action" data-cars-next>Event & Weekend Schedule <span aria-hidden="true">→</span></button></section>`:'<section class="f1-feature"><h2>Season Schedule</h2><p>No upcoming weekend is listed.</p></section>'}<div class="cars-leaders">${Object.keys(names).map(d=>`<section class="f1-feature"><p class="f1-kicker">${esc(names[d])}</p><h2>${d} Championship</h2>${sourceNote(d)}${table(standings(d).slice(0,3),['Position','Driver','Points','Gap'])}<button class="nascar-schedule-action" data-cars-points="${d}">Full Standings <span aria-hidden="true">→</span></button></section>`).join('')}</div>`;el.querySelector('[data-cars-next]')?.addEventListener('click',()=>showRaceDetails(next));el.querySelectorAll('[data-cars-points]').forEach(b=>b.onclick=()=>{division=b.dataset.carsPoints;render('standings');});}
 function points(el){const fields=['Position','Driver','Events','Wins','Top 5','Top 10','Points','Gap'],rs=standings(division).sort((a,b)=>{const v=sort==='Driver'?a.Driver.localeCompare(b.Driver):Number(a[sort])-Number(b[sort]);return (ascending?v:-v)||Number(a.Position)-Number(b.Position);});el.innerHTML=`${note()}<h2>Championship Standings</h2>${switcher()}${sourceNote(division)}${table(rs,fields)}`;el.querySelectorAll('th').forEach((th,i)=>{const f=fields[i];th.setAttribute('aria-sort',sort===f?(ascending?'ascending':'descending'):'none');th.innerHTML=`<button class="cars-sort">${f}${sort===f?(ascending?' ↑':' ↓'):''}</button>`;th.firstChild.onclick=()=>{ascending=sort===f?!ascending:['Driver','Position'].includes(f);sort=f;render('standings',true);};});}
 function teams(el){const ds=rows('Drivers').filter(d=>d.Division===division&&d.Show!=='Hide'),groups=[...new Set(ds.map(d=>d.Team||'Drivers'))];el.innerHTML=`<h2>Teams & Drivers</h2>${switcher()}<p class="f1-data-note">Season participants from published points tables. Team assignments and photos are added as available.</p>${groups.map(name=>{const t=rows('Teams').find(t=>t.Team===name);return `<section class="f1-feature cars-team" style="--cars-team:${/^#[0-9a-f]{6}$/i.test(t?.Color)?t.Color:'#397bb5'}"><h3>${img(t?.['Logo URL'])}${esc(name)}</h3><div class="cars-driver-grid">${ds.filter(d=>(d.Team||'Drivers')===name).map(d=>`<article class="cars-driver">${img(d['Headshot URL'],'cars-portrait')||'<span class="cars-shadow" aria-hidden="true"><svg viewBox="0 0 100 130"><circle cx="50" cy="30" r="21"/><path d="M12 130V94Q12 62 50 62Q88 62 88 94V130Z"/></svg></span>'}${identity(d)}</article>`).join('')}</div></section>`;}).join('')}`;}
 function results(el){const all=resultRows().filter(r=>r.Division===division),events=rows('Events').filter(e=>all.some(r=>r['Event ID']===e['Event ID'])).sort((a,b)=>b.Date.localeCompare(a.Date));if(!events.some(e=>e['Event ID']===eventId))eventId=events[0]?.['Event ID']||'';const sessions=[...new Set(all.filter(r=>r['Event ID']===eventId).map(r=>r.Session))];if(!sessions.includes(session))session=sessions[0]||'';const rs=all.filter(r=>r['Event ID']===eventId&&r.Session===session).sort((a,b)=>Number(a.Position)-Number(b.Position));el.innerHTML=`${note()}<h2>Results</h2>${switcher()}${events.length?`<div class="cars-filters"><label>Event<select id="cars-result-event">${events.map(e=>`<option value="${esc(e['Event ID'])}" ${eventId===e['Event ID']?'selected':''}>${esc(formatDate(e.Date)+' · '+e.Event)}</option>`).join('')}</select></label><label>Session<select id="cars-result-session">${sessions.map(s=>`<option ${session===s?'selected':''}>${esc(s)}</option>`).join('')}</select></label></div>${table(rs,['Position','Driver','Start','Laps','Gap','Status'])}`:'<section class="f1-feature"><h3>Results Not Yet Added</h3><p>Race classifications will appear here when available.</p></section>'}<p><a class="nascar-schedule-action" href="https://www.carsracingtour.com/2026-results-${division.toLowerCase()}/" target="_blank" rel="noopener">Official ${division} Results <span aria-hidden="true">↗</span></a></p>`;el.querySelector('#cars-result-event')?.addEventListener('change',e=>{eventId=e.target.value;render('results',true);});el.querySelector('#cars-result-session')?.addEventListener('change',e=>{session=e.target.value;render('results',true);});}
 function tracks(el){el.innerHTML=`<h2>CARS Tour Tracks</h2><div class="f1-track-grid">${allTracks.filter(t=>t.source==='cars'&&allRaces.some(r=>r.series===series&&r.trackId===t.trackId)).map(t=>`<details class="f1-feature circuit-card"><summary class="event-photo-tile">${trackPhotoMarkup(t)}<span><strong>${esc(t.name)}</strong><span class="circuit-location">${esc([t.city,t.state].filter(Boolean).join(', '))}</span></span><span class="circuit-expand">+</span></summary><div class="circuit-body">${f1TrackFullPhotoMarkup(t)}<h3>${esc(t.name)}</h3>${trackFactsMarkup(t)}</div></details>`).join('')}</div>`;}
 async function render(which='overview',prepared=false){if(!prepared)return withLoading(async()=>{await loadSeriesDetails(series);return render(which,true);},'Opening CARS Tour…');activeSeriesName=series;document.getElementById('f1-hub').hidden=true;const hub=document.getElementById('series-hub');hub.innerHTML=`<div class="hub-sticky-navigation"><div class="series-hub-hero"><p class="weekend-eyebrow">LATE MODEL STOCK CARS · PRO LATE MODELS</p><h1>CARS Tour</h1></div><nav class="nascar-hub-tabs" style="--hub-accent:#397bb5" aria-label="CARS Tour sections">${Object.entries(tabs).map(([k,v])=>`<button data-cars-tab="${k}" aria-pressed="${k===which}">${v}</button>`).join('')}</nav></div><div id="cars-hub-content"></div>`;document.getElementById('series-calendar').hidden=true;const el=hub.querySelector('#cars-hub-content');
  if(which==='schedule')renderSeries(series,false,true);else if(protectedMode()&&!['teams','tracks'].includes(which))el.innerHTML=Spoilers.note();else if(!data)el.innerHTML=`<section class="f1-feature"><h2>CARS Tour</h2><p>${esc(error||'The CARS Tour data connection is being prepared.')}</p></section>`;else ({overview,standings:points,teams,results,tracks}[which]||overview)(el);
  hub.hidden=false;setView('series-view');document.getElementById('back-button').hidden=true;hub.querySelectorAll('[data-cars-tab]').forEach(b=>b.onclick=()=>render(b.dataset.carsTab));hub.querySelectorAll('[data-cars-division]').forEach(b=>b.onclick=()=>{division=b.dataset.carsDivision;render(which,true);});const active=hub.querySelector('[data-cars-tab][aria-pressed="true"]');alignSeriesTab(active);if(which==='schedule')focusScheduleRace();
 }
 function openResults(id,d,s){eventId=id;division=d;session=s;return render('results');}
 function home(card){if(!data||protectedMode())return;const el=document.createElement('div');el.className='cars-home-summary';el.innerHTML=Object.keys(names).map(d=>{const r=standings(d)[0];return r?`<div class="f1-home-leader" data-home-action="standings" role="link" tabindex="0"><p><span>${d} Championship Leaders</span><strong>${esc(profile(r)?.Driver||r.Driver)}</strong><small>${esc(r.Points)} pts · As of ${esc(formatDate(r['As Of']))}</small></p>${img(profile(r)?.['Headshot URL'],'f1-home-portrait')}</div>`:'';}).join('');card.appendChild(el);}
 function eventLinks(race){if(!data||protectedMode())return [];const rs=resultRows().filter(r=>r['Event ID']===race.carsEventId);return [...new Map(rs.map(r=>[r.Division+' '+r.Session,r])).values()].map(r=>{const winner=rs.find(w=>w.Division===r.Division&&w.Session===r.Session&&Number(w.Position)===1);return {label:r.Division+' '+r.Session+' Results',session:r.Division+' '+r.Session,leader:winner?.Driver||'',leaderLabel:/qual/i.test(r.Session)?'Pole Sitter':'Winner',open:()=>openResults(race.carsEventId,r.Division,r.Session)};});}
 return {refreshResults:el=>{if(!protectedMode())results(el);},configured,load,install,render,home,eventLinks,enabled:()=>!!data,raceCompleted:race=>{const ss=rows('Sessions').filter(s=>s['Event ID']===race.carsEventId&&s.Session==='Race'&&s.Status!=='Cancelled');return !!ss.length&&ss.every(s=>resultRows().some(r=>r['Event ID']===s['Event ID']&&r.Division===s.Division&&r.Session==='Race'));}};
})();
