/* Endurance racing is classified by car and class, not a single-driver grid. */
const IMSAHub=(()=>{
 const series='IMSA',tabs={overview:'Overview',schedule:'Schedule',standings:'Standings',teams:'Teams & Drivers',results:'Results',tracks:'Tracks'};
 let data=null,loaded=0,pending=null,error='',selectedClass='GTP',selectedEvent='',selectedSession='';
 const esc=x=>escapeHtml(x??''),year=()=>String(new Date().getFullYear()),configured=()=>!!window.RC_IMSA_CONFIG?.feedUrl;
 const rows=k=>(data?.[k]||[]).filter(r=>k==='Status'||String(r.Season)===year()),norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');
 const cls=s=>String(s||'').toUpperCase().replace(/^GTD\s*PRO$/,'GTD PRO'),protectedMode=()=>typeof Spoilers!=='undefined'&&Spoilers.protected(series);
 const safe=s=>{try{const u=new URL(s);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'';}catch{return '';}};
 const img=(s,c='imsa-logo')=>safe(s)?`<img src="${esc(safe(s))}" class="${c}" alt="" loading="lazy" onerror="this.hidden=true">`:'';
 const entry=(n,c=selectedClass)=>rows('Entries').find(e=>e.Number===n&&cls(e.Class)===cls(c)),team=e=>e?.['Team Name Override']||e?.Team||'',crew=n=>rows('Drivers').filter(d=>d.Current!=='FALSE'&&d['Entry ID']===(entry(n)?.['Entry ID']||n)),driverName=d=>d['Display Name Override']||d.Driver;
 const classLabel=c=>cls(c)==='GTP'?'GTP':c;
 const identity=r=>{const e=entry(r.Number,r.Class);return `<span class="imsa-identity"><b class="imsa-number">#${esc(r.Number)}</b><span><strong>${esc(r.Team||team(e))}</strong><small>${esc(e?.Model||e?.Manufacturer||'')}</small></span></span>`;};
 const classes=()=>['GTP','LMP2','GTD PRO','GTD'];
 function classSwitch(){return `<div class="imsa-class-switch" role="group" aria-label="Racing class">${classes().map(c=>`<button data-imsa-class="${esc(c)}" aria-pressed="${c===selectedClass}">${esc(classLabel(c))}</button>`).join('')}</div>`;}
 function note(){const status=rows('Status')[0];return `${error?`<p class="f1-warning">${esc(error)}</p>`:''}<p class="f1-data-note">${esc(RaceDisplay.feedNote(status,rows('Events'),rows('Results')))}</p>`;}
 async function load(){if(!configured())return;if(pending)return pending;if(data&&Date.now()-loaded<60000)return;
 pending=(async()=>{try{const raw=await fetchSheet(window.RC_IMSA_CONFIG.feedUrl),next={};for(const r of raw){if(!['Events','Sessions','Tracks','Entries','Drivers','Standings','Results','Status'].includes(r.Kind))continue;const v=JSON.parse(r.Data);if(!v||typeof v!=='object'||Array.isArray(v))throw Error('Invalid IMSA row');(next[r.Kind]??=[]).push(v);}if(!next.Events?.length)throw Error('Incomplete IMSA feed');data=next;loaded=Date.now();error='';}catch(e){error='IMSA update unavailable. '+(data?'Showing the last loaded data.':'The existing schedule is still available.');console.warn('IMSA',e.message);}finally{pending=null;}})();return pending;}
 function eastern(iso){const d=new Date(iso);if(!iso||!Number.isFinite(d.getTime()))return {date:'',time:'TBD'};return {date:new Intl.DateTimeFormat('en-CA',{timeZone:'America/New_York',year:'numeric',month:'2-digit',day:'2-digit'}).format(d),time:d.toLocaleTimeString('en-US',{timeZone:'America/New_York',hour:'numeric',minute:'2-digit'})};}
 function install(){if(!data)return;
 const tracks=rows('Tracks').map(t=>{const shared=allTracks.find(x=>t['Shared Track Source']&&t['Shared Track ID']&&x.source===t['Shared Track Source']&&String(x.trackId)===t['Shared Track ID']);return {...shared,source:'imsa',trackId:'imsa-'+t['Track ID'],name:t['Track Name Override']||shared?.name||t['Track Name'],city:t.City||shared?.city,state:t.Country||shared?.state,type:t['Track Type']||shared?.type,length:t['Track Length']||shared?.length,imageUrl:t['Track Image URL']||shared?.imageUrl,mapUrl:t['Track Map URL']||shared?.mapUrl};});
 const races=[],sessions=[];
 for(const e of rows('Events')){const ss=rows('Sessions').filter(s=>s['Event ID']===e['Event ID']),raceSession=ss.find(s=>/^race$/i.test(s.Session)),start=e['Race Start UTC Override']||raceSession?.['Start UTC Override']||raceSession?.['Start UTC'],when=eastern(start);
 const r={series,raceId:'imsa-'+e['Event ID'],imsaEventId:e['Event ID'],round:e.Round,event:e['Event Override']||e.Event,trackId:'imsa-'+e['Track ID'],date:when.date||e['Race Date']||e['End Date'],time:when.time,network:e.Network||'',notes:[e.Notes,e.Classes].filter(Boolean).join(' · '),durationHours:e['Duration Hours Override']||e['Duration Hours']};races.push(r);
 for(const ssn of ss){const time=eastern(/^race$/i.test(ssn.Session)?start:ssn['Start UTC Override']||ssn['Start UTC']);sessions.push({series,raceId:r.raceId,trackId:r.trackId,session:ssn.Session,type:/^race$/i.test(ssn.Session)?'Race':/qual/i.test(ssn.Session)?'Qualifying':'Practice',date:time.date||e['Start Date'],time:time.time,notes:ssn.Status==='Cancelled'?'Cancelled':''});}
 if(!raceSession)sessions.push({series,raceId:r.raceId,trackId:r.trackId,session:'Race',type:'Race',date:r.date,time:r.time,notes:'Weekend timetable awaiting publication'});
 }
 allRaces=allRaces.filter(r=>r.series!==series).concat(races);allSessions=allSessions.filter(r=>r.series!==series).concat(sessions);allTracks=allTracks.filter(t=>t.source!=='imsa').concat(tracks);
 }
 const duration=h=>{const m=Math.round(Number(h)*60);return m%60?Math.floor(m/60)+'h '+m%60+'m':m/60+' Hours';};
 const resultRows=()=>rows('Results').sort((a,b)=>Number(rows('Events').find(e=>e['Event ID']===b['Event ID'])?.Round)-Number(rows('Events').find(e=>e['Event ID']===a['Event ID'])?.Round)||(Number(a.Position)||999)-(Number(b.Position)||999));
 function standings(category,limit){const rs=rows('Standings').filter(r=>r.Category===category).sort((a,b)=>Number(a.Position)-Number(b.Position));return `<div class="f1-table-wrap"><table class="imsa-table"><thead><tr><th>Pos</th><th>${/Drivers/.test(category)?'Drivers':'Competitor'}</th><th>Points</th><th>Behind</th></tr></thead><tbody>${rs.slice(0,limit||rs.length).map(r=>`<tr><td>${esc(r.Position)}</td><td><span class="imsa-standing-name">${img(r['Logo URL'])}<span>${r.Number?`<b>#${esc(r.Number)}</b> `:''}${esc(r.Name)}</span></span></td><td><strong>${esc(r.Points)}</strong></td><td>${Number(r.Position)===1?'—':'−'+(Number(rs[0].Points)-Number(r.Points))}</td></tr>`).join('')}</tbody></table></div>`;}
 function overview(el){const next=racesFor(series).find(r=>r.date>localIsoDate()||(r.date===localIsoDate()&&raceStartTime(r)>=Date.now())),last=resultRows().find(r=>/^race$/i.test(r.Session)&&cls(r.Class)===selectedClass),cats=[...new Set(rows('Standings').filter(r=>cls(r.Class)===selectedClass).map(r=>r.Category))];
 el.innerHTML=`${note()}${next?`<section class="f1-feature event-photo-tile imsa-next">${racePhotoMarkup(next)}<p class="f1-kicker">Next WeatherTech Race</p><h2>${esc(next.event)}</h2><p>${esc(trackNameForRace(next))}</p><p>${formatDate(next.date)} · ${esc(RaceDisplay.time(next.time))}</p>${next.durationHours?`<span class="imsa-duration">${esc(duration(next.durationHours))} · Scheduled</span>`:''}${next.network?`<p>Network: ${esc(next.network)}</p>`:''}<button class="nascar-schedule-action" data-imsa-next>Event & Weekend Schedule <span aria-hidden="true">→</span></button></section>`:'<section class="f1-feature"><h2>Season Schedule</h2><p>No upcoming race is listed.</p></section>'}${classSwitch()}<p class="imsa-explainer">Multiple classes share the track. Results and podiums below are for ${esc(classLabel(selectedClass))}; each car is shared by its driver crew.</p>${last?`<button class="f1-feature imsa-overview-link" data-imsa-latest><p class="f1-kicker">Latest ${esc(classLabel(selectedClass))} Podium</p><h2>${esc(rows('Events').find(e=>e['Event ID']===last['Event ID'])?.Event)}</h2>${resultRows().filter(r=>r['Event ID']===last['Event ID']&&r['Session ID']===last['Session ID']&&cls(r.Class)===selectedClass&&Number(r.Position)>=1&&Number(r.Position)<=3).map(r=>`<span class="imsa-podium"><b>${esc(r.Position)}</b>${identity(r)}<small>${esc(r.Laps)} Laps</small></span>`).join('')}<span class="home-panel-cta">Full Class Results →</span></button>`:'<p>No published race results imported for this class yet.</p>'}${cats.map(c=>`<section class="f1-feature"><button class="imsa-section-link" data-imsa-standings><h2>${esc(c)}</h2><span>Full Standings →</span></button>${standings(c,3)}</section>`).join('')}`;
 el.querySelector('[data-imsa-next]')?.addEventListener('click',()=>showRaceDetails(next));el.querySelector('[data-imsa-latest]')?.addEventListener('click',()=>openResults(last['Event ID'],last['Session ID'],selectedClass));el.querySelectorAll('[data-imsa-standings]').forEach(b=>b.onclick=()=>render('standings'));
 }
 function teams(el){const es=rows('Entries').filter(e=>cls(e.Class)===selectedClass),groups=[...new Set(es.map(team))];el.innerHTML=`${note()}<h2>Teams & Driver Crews</h2>${classSwitch()}<p class="imsa-explainer">Car entries share a team, but each car has its own crew and classification. Crews shown are from each car’s latest imported session; endurance lineups can change between races.</p>${groups.map(t=>{const list=es.filter(e=>team(e)===t),first=list[0];return `<section class="f1-feature imsa-team"><h3>${img(first['Team Logo URL Override']||first['Logo URL'])}${esc(t)}</h3><div class="imsa-entry-grid">${list.map(e=>`<article class="imsa-entry" style="--entry-accent:${/^#[0-9a-f]{6}$/i.test(e['Color Override'])?e['Color Override']:'#c8383d'}"><header><b class="imsa-number">#${esc(e.Number)}</b><span>${esc(e.Model||e.Manufacturer)}<small>${esc(classLabel(e.Class))}</small></span></header>${img(e['Car Image URL'],'imsa-car')}<div class="imsa-crew">${crew(e.Number).map(d=>`<div>${img(d['Headshot URL Override']||d['Headshot URL'],'imsa-portrait')||'<span class="imsa-placeholder" aria-hidden="true"><svg viewBox="0 0 100 130"><circle cx="50" cy="32" r="21"/><path d="M12 130V94Q12 63 50 63Q88 63 88 94V130Z"/></svg></span>'}<strong>${esc(driverName(d))}</strong><small>${esc(d.Country)} · ${esc(d.License)}</small></div>`).join('')||'<p>Driver crew is being imported.</p>'}</div></article>`).join('')}</div></section>`;}).join('')}`;}
 function results(el){const rs=resultRows(),events=rows('Events').filter(e=>rs.some(r=>r['Event ID']===e['Event ID'])).sort((a,b)=>Number(b.Round)-Number(a.Round));if(!events.length){el.innerHTML=`${note()}<h2>Results</h2><p>Published results are being imported.</p>`;return;}
 if(!events.some(e=>e['Event ID']===selectedEvent))selectedEvent=events[0]['Event ID'];const choices=[...new Map(rs.filter(r=>r['Event ID']===selectedEvent).map(r=>[r['Session ID'],r])).values()].sort((a,b)=>/^race$/i.test(a.Session)?-1:/^race$/i.test(b.Session)?1:Number(b['Session ID'])-Number(a['Session ID']));
 if(!choices.some(r=>r['Session ID']===selectedSession))selectedSession=choices[0]['Session ID'];const available=[...new Set(rs.filter(r=>r['Event ID']===selectedEvent&&r['Session ID']===selectedSession).map(r=>cls(r.Class)))];if(!available.includes(selectedClass))selectedClass=available[0];
 const selected=rs.filter(r=>r['Event ID']===selectedEvent&&r['Session ID']===selectedSession&&cls(r.Class)===selectedClass),race=/^race$/i.test(selected[0]?.Session);
 el.innerHTML=`${note()}<h2>Results</h2><div class="imsa-filters"><label>Event<select id="imsa-result-event">${events.map(e=>`<option value="${esc(e['Event ID'])}" ${e['Event ID']===selectedEvent?'selected':''}>Round ${esc(e.Round)} · ${esc(e['Event Override']||e.Event)} · ${esc(e['Track Name'])}</option>`).join('')}</select></label><label>Session<select id="imsa-result-session">${choices.map(r=>`<option value="${esc(r['Session ID'])}" ${r['Session ID']===selectedSession?'selected':''}>${esc(r.Session)}</option>`).join('')}</select></label><label>Class<select id="imsa-result-class">${available.map(c=>`<option ${c===selectedClass?'selected':''}>${esc(c)}</option>`).join('')}</select></label></div><p class="f1-data-note">Positions are within ${esc(classLabel(selectedClass))}. Gaps and intervals are to the overall leader and previous car. Crews below belong to this session. ${esc(selected[0]?.['Report Status']||'')} classification.</p><div class="f1-table-wrap"><table class="imsa-table"><thead><tr><th>Class Pos</th><th>Car / Team</th><th>Laps</th><th>${race?'Total Time':'Best Lap'}</th><th>Gap</th><th>Interval</th>${race?'<th>Best Lap</th>':''}<th>Pit Stops</th><th>Status</th></tr></thead><tbody>${selected.map(r=>`<tr><td>${esc(r.Position)}</td><td>${identity(r)}<small class="imsa-result-crew">${esc(r.Crew)}</small></td><td>${esc(r.Laps||'—')}</td><td>${esc(r.Time||'—')}</td><td>${esc(r.Gap||'—')}</td><td>${esc(r.Interval||'—')}</td>${race?`<td>${esc(r['Best Lap']||'—')}</td>`:''}<td>${esc(r['Pit Stops']||'—')}</td><td>${esc(r.Status||'—')}</td></tr>`).join('')}</tbody></table></div>`;
 el.querySelector('#imsa-result-event').onchange=e=>{selectedEvent=e.target.value;selectedSession='';results(el);};el.querySelector('#imsa-result-session').onchange=e=>{selectedSession=e.target.value;results(el);};el.querySelector('#imsa-result-class').onchange=e=>{selectedClass=e.target.value;results(el);};}
 function tracks(el){const list=allTracks.filter(t=>t.source==='imsa');el.innerHTML=`<h2>IMSA Tracks</h2><div class="f1-track-grid">${list.map(t=>`<details class="f1-feature circuit-card"><summary class="event-photo-tile">${trackPhotoMarkup(t)}<span><strong>${esc(t.name)}</strong><span class="circuit-location">${esc([t.city,t.state].filter(Boolean).join(', '))}</span></span><span class="circuit-expand">+</span></summary><div class="circuit-body">${f1TrackFullPhotoMarkup(t)}<h3>${esc(t.name)}</h3>${trackFactsMarkup(t)}</div></details>`).join('')}</div>`;}
 async function render(which='overview',prepared=false){if(!prepared)return withLoading(async()=>{await loadSeriesDetails(series);return render(which,true);},'Opening IMSA…');activeSeriesName=series;document.getElementById('f1-hub').hidden=true;const hub=document.getElementById('series-hub');hub.innerHTML=`<div class="hub-sticky-navigation"><div class="series-hub-hero">${seriesLogoMarkup(series,true)}<p class="weekend-eyebrow">WEATHERTECH SPORTSCAR CHAMPIONSHIP</p><h1>IMSA</h1></div><nav class="nascar-hub-tabs" style="--hub-accent:#c8383d" aria-label="IMSA sections">${Object.entries(tabs).map(([k,v])=>`<button data-imsa-tab="${k}" aria-pressed="${k===which}">${v}</button>`).join('')}</nav></div><div id="imsa-hub-content"></div>`;document.getElementById('series-calendar').hidden=true;const el=hub.querySelector('#imsa-hub-content');el.className='imsa-view-'+which;
 if(which==='schedule')renderSeries(series,false,true);else if(protectedMode()&&!['teams','tracks'].includes(which))el.innerHTML=Spoilers.note();else if(!data)el.innerHTML=`<section class="f1-feature"><h2>IMSA Hub</h2><p>${configured()?esc(error||'IMSA data is unavailable.'):'The IMSA data connection is being prepared. The existing schedule is available now.'}</p>${configured()?'<button class="nascar-schedule-action" data-imsa-retry>Try Again</button>':''}</section>`;else if(which==='overview')overview(el);else if(which==='teams')teams(el);else if(which==='results')results(el);else if(which==='tracks')tracks(el);else el.innerHTML=`${note()}<h2>Championship Standings</h2>${classSwitch()}<p class="imsa-explainer">Official championship points. Drivers have individual points totals. Team standings belong to each car entry. Manufacturer points are shown only for classes with an official classification.</p>${!rows('Standings').length?'<p>Official standings have not been imported yet.</p>':''}${[...new Set(rows('Standings').filter(r=>cls(r.Class)===selectedClass).map(r=>r.Category))].map(c=>`<section class="f1-feature"><h3>${esc(c)}</h3>${standings(c)}</section>`).join('')}`;
 hub.hidden=false;setView('series-view');document.getElementById('back-button').hidden=true;hub.querySelectorAll('[data-imsa-tab]').forEach(b=>b.onclick=()=>render(b.dataset.imsaTab));hub.querySelectorAll('[data-imsa-class]').forEach(b=>b.onclick=()=>{selectedClass=b.dataset.imsaClass;render(which,true);});hub.querySelector('[data-imsa-retry]')?.addEventListener('click',()=>{loaded=0;render(which);});const active=hub.querySelector('[aria-pressed="true"]');alignSeriesTab(active);if(which==='schedule')focusScheduleRace();}
 function openResults(event,session,c){selectedEvent=String(event);selectedSession=String(session||'');if(c)selectedClass=cls(c);return render('results');}
 function home(card){if(!data||protectedMode())return;const first=rows('Standings').filter(r=>Number(r.Position)===1&&/Drivers/.test(r.Category));const leaders=classes().map(c=>{const tied=first.filter(r=>cls(r.Class)===c);return tied.length?{...tied[0],Name:tied.map(r=>r.Name).join(' / ')}:null;}).filter(Boolean);const el=document.createElement('div');el.className='imsa-home-summary';el.innerHTML=leaders.map(r=>`<div class="f1-home-leader" data-home-action="standings" role="link" tabindex="0"><p><span>${esc(classLabel(r.Class))} Championship Leaders</span><strong>${esc(r.Name)}</strong><small>${r.Number?'#'+esc(r.Number)+' · ':''}${esc(r.Points)} pts</small></p>${img(r['Logo URL'],'f1-home-team-logo')}</div>`).join('');card.appendChild(el);const last=resultRows().find(r=>/^race$/i.test(r.Session)&&cls(r.Class)==='GTP'&&Number(r.Position)===1),race=last&&racesFor(series).find(r=>r.imsaEventId===last['Event ID']);if(race)homePreviousPanel(card,race,`<small>GTP Winner</small>${identity(last)}`,()=>openResults(last['Event ID'],last['Session ID'],'GTP'));}
 function eventLinks(race){if(!data||protectedMode())return [];const id=race.imsaEventId||rows('Events').find(e=>race.date>=e['Start Date']&&race.date<=e['End Date'])?.['Event ID'];const rs=resultRows().filter(r=>r['Event ID']===id);return [...new Map(rs.map(r=>[r['Session ID']+'|'+r.Class,r])).values()].map(r=>{const winner=rs.find(x=>x['Session ID']===r['Session ID']&&x.Class===r.Class&&Number(x.Position)===1);return {label:classLabel(r.Class)+' '+r.Session+' Results',session:r.Session,leader:winner?'#'+winner.Number+' '+winner.Team:'',leaderLabel:classLabel(r.Class)+' '+(/^race$/i.test(r.Session)?'Winner':/qual/i.test(r.Session)?'Pole sitter':'Session leader'),open:()=>openResults(id,r['Session ID'],r.Class)};});}
 return {refreshResults:el=>{if(!protectedMode())results(el);},configured,load,install,enabled:()=>!!data,render,home,eventLinks,raceCompleted:race=>!!data&&rows('Results').some(r=>r['Event ID']===race.imsaEventId&&/^race$/i.test(r.Session)&&Number(r.Position)>0)};
})();
